### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by michaelsanford** [isaacs/tap-results#1]
Please specify a license under which this module is released.

In some jurisdictions, lack of an explicit license implies copyright without terms of use, which can be an unnecessary hindrance during due diligence (as you probably intended for this module to be used openly).

If you're looking for suggestions: MIT or WTFPL would suit nicely.

See https://github.com/isaacs/tap-consumer/issues/4

**Comment by isaacs** [comment]
Since this module is deprecated, it's a bad idea to be using it anyway.

Please use [node-tap](https://github.com/isaacs/node-tap) instead.

**Comment by michaelsanford** [comment]
For completeness: it's a second-tier dependency, so I cannot choose whether it's included in my own project but legal cares about the entire dependency tree. I guess I'll ping the module owner.

Thanks for your prompt reply, @isaacs.
